//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elective {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elective.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все сообщения.
        /// </summary>
        public static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить вход.
        /// </summary>
        public static string Autorize {
            get {
                return ResourceManager.GetString("Autorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string AutorizeButton {
            get {
                return ResourceManager.GetString("AutorizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создайте новую учетную запись..
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общеуниверситетские факультативы.
        /// </summary>
        public static string GeneralUniversityElectives {
            get {
                return ResourceManager.GetString("GeneralUniversityElectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общеуниверситетские факультативы — давняя традиция ХНУРЕ, и этой хорошей традиции уже более 10 лет.
        ///    Каждый учебный год Университет организует учебные курсы различной тематики и продолжительности: от сугубо теоретических
        ///    до мастер-классов ведущих практиков. Задача общеуниверситетского факультатива — не столько передача знания, сколько формирование
        ///    особого мировоззрения и получение дополнительных компетенций, необходимых для дальнейшей профессиональной деятельности студента..
        /// </summary>
        public static string GeneralUniversityElectivesParagraph1 {
            get {
                return ResourceManager.GetString("GeneralUniversityElectivesParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любой студент ХНУРЕ может самостоятельно выбрать для изучения любой общеуниверситетский факультатив. Общеуниверситетский
        ///    факультатив изучается вне рамок основной образовательной программы. Это значит, что неудовлетворительная оценка не будет являться
        ///    академической задолженностью (в соответствии с Положением об организации промежуточной аттестации и текущего контроля успеваемости
        ///    студентов. Оценка „неудовлетворительно“, полученная по общеуниверситетскому факультативу, не считается академическо [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string GeneralUniversityElectivesParagraph2 {
            get {
                return ResourceManager.GetString("GeneralUniversityElectivesParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Факультативы также открыты для всех внешних заинтересованных слушателей независимо от возраста и уровня обучения..
        /// </summary>
        public static string GeneralUniversityElectivesParagraph3 {
            get {
                return ResourceManager.GetString("GeneralUniversityElectivesParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В рамках общеуниверситетских факультативов в 2017/18 учебном году студентам и аспирантам,
        ///    а также всем заинтересованным слушателям извне предлагается 50 авторских курсов, представляющих
        ///    панораму актуальных исследований по экономике и управлению, технике, математике и естествознанию,
        ///    а также в области гуманитарных и социальных наук..
        /// </summary>
        public static string GeneralUniversityElectivesParagraph4 {
            get {
                return ResourceManager.GetString("GeneralUniversityElectivesParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посещение факультативов для всех слушателей бесплатно..
        /// </summary>
        public static string GeneralUniversityElectivesParagraph5 {
            get {
                return ResourceManager.GetString("GeneralUniversityElectivesParagraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По всем вопросам, связанным с реализацией общеуниверситетских факультативов, пишите в Дирекцию основных образовательных программ (electives@nure.ua)..
        /// </summary>
        public static string GeneralUniversityElectivesParagraph6 {
            get {
                return ResourceManager.GetString("GeneralUniversityElectivesParagraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домашняя страница.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть.
        /// </summary>
        public static string Look {
            get {
                return ResourceManager.GetString("Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полученные сообщения.
        /// </summary>
        public static string MailReceive {
            get {
                return ResourceManager.GetString("MailReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить сообщение.
        /// </summary>
        public static string MailSend {
            get {
                return ResourceManager.GetString("MailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое сообщения.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация нового пользователя.
        /// </summary>
        public static string RegisterNewAccount {
            get {
                return ResourceManager.GetString("RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
    }
}
